
services:
  asterisk:
    image: andrius/asterisk
    container_name: asterisk
    restart: always
    ports:
      - "5060:5060/udp"
      - "8088:8088"
    volumes:
      - ./configs:/etc/asterisk

